version: '2'
services:
  broker:
    hostname: "rabbitmq.com"
    image: "rabbitmq:3"
    ports:
      - 5672:5672
    networks:
      - mynet
  web:
    #image: msrajpurohit/rest_users
    hostname: "webserver.com"
    build:
     context: .
    ports:
      - 8000:8000
    networks:
      - mynet
    volumes:
      - '/tmp:/db'
  celery:
    hostname: "celery-workers.com"
    build:
      context: .
    command: celery worker -A rest_users_mgmt --loglevel=INFO
    networks:
      - mynet
    volumes:
      - '/tmp:/db'
networks:
  mynet:
    driver: bridge
